### ISSUE TITLE
Bug lors de la création d'une nouvelle configuration

### ISSUE THREAD

**Issue by MrAnyx** [Buissartt/Linux-autohost#4]
**Describe the bug**
Il faut d'abord start le service apache pour pouvoir le reload. Il faudrait changer le reload pour un restart ou bien démarrer le service apache au début du script. Il y a le même problème avec mysql

**To Reproduce**
- Start linux
- don't start apache2 or mysql
- create a new configuration

**Expected behavior**
ne pas mettre de message d'erreur lorsque le service n'est pas lancé

**Screenshots**

![image](https://user-images.githubusercontent.com/44176707/107128395-9a31e180-68bd-11eb-8fa6-75bdb28d8e86.png)

**Desktop (please complete the following information):**
- WSL 2 (Ubuntu 20.04 LTS)

**Comment by Buissartt** [comment]
Je pense qu'en correctif faire un `if(serviceIsRunning) reload;` suffirait. Si jamais le service ne tourne pas, le script ne fait rien car les modifications seront prisent en compte au prochain démarrage.
